/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;


/**
 *
 * @author mangg
 * Kelas : 3D
 * NIM : 21090118
 */
public class GUIcalc extends javax.swing.JFrame {
    
    double angka1;
    double angka2;
    String OP;
    
    private void keterangan(String ket){
        String ang = Keterangan.getText()+ket;
        Keterangan.setText(ang);
        
    }
    
    private void inputNumber(String num){
        String numS = jHasil.getText() + num;
        jHasil.setText(numS);
    }
    /**
     * Creates new form GUIcalc
     */
    public GUIcalc() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHasil = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        number1 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number00 = new javax.swing.JButton();
        jBackS = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        inputTitik = new javax.swing.JButton();
        jResult = new javax.swing.JButton();
        jBagi = new javax.swing.JButton();
        jKali = new javax.swing.JButton();
        jKurang = new javax.swing.JButton();
        jTambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Keterangan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Sederhana\n");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jHasil.setEditable(false);
        jHasil.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jHasil.setForeground(new java.awt.Color(51, 255, 0));
        jHasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jHasil.setActionCommand("<Not Set>");
        jHasil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jHasil.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHasilActionPerformed(evt);
            }
        });
        getContentPane().add(jHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 82));

        number1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number1.setText("1");
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number4.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number4.setText("4");
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });

        number7.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number7.setText("7");
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        number0.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number0.setText("0");
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });

        jClear.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jClear.setText("C");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        number2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number2.setText("2");
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });

        number5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number5.setText("5");
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });

        number8.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number8.setText("8");
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        number00.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number00.setText("00");
        number00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number00ActionPerformed(evt);
            }
        });

        jBackS.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jBackS.setText("X");
        jBackS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackSActionPerformed(evt);
            }
        });

        number3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number3.setText("3");
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });

        number6.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number6.setText("6");
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });

        number9.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        number9.setText("9");
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });

        inputTitik.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        inputTitik.setText(".");
        inputTitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTitikActionPerformed(evt);
            }
        });

        jResult.setBackground(new java.awt.Color(153, 255, 255));
        jResult.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jResult.setText("=");
        jResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResultActionPerformed(evt);
            }
        });

        jBagi.setBackground(new java.awt.Color(255, 153, 51));
        jBagi.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jBagi.setText("/");
        jBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagiActionPerformed(evt);
            }
        });

        jKali.setBackground(new java.awt.Color(153, 153, 255));
        jKali.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jKali.setText("*");
        jKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKaliActionPerformed(evt);
            }
        });

        jKurang.setBackground(new java.awt.Color(255, 0, 51));
        jKurang.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jKurang.setText("-");
        jKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKurangActionPerformed(evt);
            }
        });

        jTambah.setBackground(new java.awt.Color(0, 204, 51));
        jTambah.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jTambah.setText("+");
        jTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTambahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 8)); // NOI18N
        jLabel1.setText("@21090118");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBackS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jKali, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(number00, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jKali, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBackS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, -1, -1));

        Keterangan.setEditable(false);
        Keterangan.setForeground(new java.awt.Color(153, 153, 153));
        Keterangan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Keterangan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        getContentPane().add(Keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 350, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        // TODO add your handling code here:
        inputNumber("1");
        keterangan("1");
        
    }//GEN-LAST:event_number1ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        // TODO add your handling code here:
        inputNumber("4");
        keterangan("4");
    }//GEN-LAST:event_number4ActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        // TODO add your handling code here:
        inputNumber("7");
        keterangan("7");
    }//GEN-LAST:event_number7ActionPerformed

    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
        // TODO add your handling code here:
        inputNumber("0");
        keterangan("0");
    }//GEN-LAST:event_number0ActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
        jHasil.setText("");
        Keterangan.setText("");
        
    }//GEN-LAST:event_jClearActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        // TODO add your handling code here:
        inputNumber("2");
        keterangan("2");
    }//GEN-LAST:event_number2ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        // TODO add your handling code here:
        inputNumber("5");
        keterangan("5");
    }//GEN-LAST:event_number5ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        // TODO add your handling code here:
        inputNumber("8");
        keterangan("8");
    }//GEN-LAST:event_number8ActionPerformed

    private void number00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number00ActionPerformed
        // TODO add your handling code here:
        inputNumber("00");
        keterangan("00");
    }//GEN-LAST:event_number00ActionPerformed

    private void jBackSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackSActionPerformed
        // TODO add your handling code here:
        String backS = null;
        if (jHasil.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(jHasil.getText());
            sb.deleteCharAt(jHasil.getText().length() - 1);
            backS = sb.toString();
            jHasil.setText(backS);
            
        }
        String backSS = null;
        if (Keterangan.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(Keterangan.getText());
            sb.deleteCharAt(Keterangan.getText().length() - 1);
            backSS = sb.toString();
            Keterangan.setText(backSS);
            
        }
    }//GEN-LAST:event_jBackSActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        // TODO add your handling code here:
        inputNumber("3");
        keterangan("3");
    }//GEN-LAST:event_number3ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        // TODO add your handling code here:
        inputNumber("6");
        keterangan("6");
    }//GEN-LAST:event_number6ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        // TODO add your handling code here:
        inputNumber("9");
        keterangan("9");
    }//GEN-LAST:event_number9ActionPerformed

    private void inputTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTitikActionPerformed
        // TODO add your handling code here:
        keterangan(".");
        if (!jHasil.getText().contains(".")) {
            jHasil.setText(jHasil.getText() + inputTitik.getText()); 
        }
    }//GEN-LAST:event_inputTitikActionPerformed

    private void jResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResultActionPerformed
        // TODO add your handling code here:
        angka2 = Double.parseDouble(jHasil.getText());
        double hasil;
        hasil = Methods.Perhitungan(OP, angka1, angka2);
        String resulq = String.valueOf(hasil);
        String hasil_hitung;
            if(hasil %1 == 0){
                    hasil_hitung = resulq.substring(0,resulq.lastIndexOf("."));
                
                }else {
                    hasil_hitung = resulq;
                }
            
        jHasil.setText(hasil_hitung);

           
    }//GEN-LAST:event_jResultActionPerformed

    private void jBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagiActionPerformed
        // TODO add your handling code here:
        keterangan("/");
        angka1 = Double.parseDouble(jHasil.getText());
        jHasil.setText("");
        OP = "/";
    }//GEN-LAST:event_jBagiActionPerformed

    private void jKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKaliActionPerformed
        // TODO add your handling code here:
        keterangan("*");
        angka1 = Double.parseDouble(jHasil.getText());
        jHasil.setText("");
        OP = "*";
    }//GEN-LAST:event_jKaliActionPerformed

    private void jKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKurangActionPerformed
        // TODO add your handling code here:
        keterangan("-");
        angka1 = Double.parseDouble(jHasil.getText());
        jHasil.setText("");
        OP = "-";
    }//GEN-LAST:event_jKurangActionPerformed

    private void jTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahActionPerformed
        // TODO add your handling code here:
        keterangan("+");
        angka1 = Double.parseDouble(jHasil.getText());
        jHasil.setText("");
        OP = "+";
        
    }//GEN-LAST:event_jTambahActionPerformed

    private void jHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIcalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Keterangan;
    private javax.swing.JButton inputTitik;
    private javax.swing.JButton jBackS;
    private javax.swing.JButton jBagi;
    private javax.swing.JButton jClear;
    private javax.swing.JTextField jHasil;
    private javax.swing.JButton jKali;
    private javax.swing.JButton jKurang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jResult;
    private javax.swing.JButton jTambah;
    private javax.swing.JButton number0;
    private javax.swing.JButton number00;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    // End of variables declaration//GEN-END:variables
}
